# Generated by Django 4.1.7 on 2023-03-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='tags',
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(max_length=1500),
        ),
    ]
