# Generated by Django 4.1.7 on 2023-03-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0005_alter_quote_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='quotes_app.tag'),
        ),
    ]
